// Generated by CoffeeScript 1.7.1
(function() {
  var assert;

  assert = chai.assert;


  /*
  describe "deck constructor", ->
  
    it "should create a card collection", ->
      collection = new Deck()
      assert.strictEqual collection.length, 52
   */

  describe("Score Handling", function() {
    return it("should handle Aces correctly", function() {
      var hand1;
      hand1 = new Hand([1, 0]);
      console.log(hand1);
      assert.strictEqual(hand1.scores()[0], 3);
      return assert.strictEqual(hand1.scores()[1], 13);
    });
  });

}).call(this);

//# sourceMappingURL=BlackjackViewSpec.map
